# Generated by Django 4.2.12 on 2024-05-15 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('IdCase', models.AutoField(primary_key=True, serialize=False)),
                ('CaseSerial', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
                ('Observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('IdEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('SistemaOperativo', models.CharField(max_length=100)),
                ('IP', models.CharField(max_length=16, null=True)),
                ('Descripcion', models.CharField(max_length=500)),
                ('Case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.case')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('IdImpresora', models.AutoField(primary_key=True, serialize=False)),
                ('ImpresoraSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('IdMonitor', models.AutoField(primary_key=True, serialize=False)),
                ('MonitorSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Resolucion', models.CharField(max_length=50)),
                ('FechaIngreso', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parlante',
            fields=[
                ('IdParlante', models.AutoField(primary_key=True, serialize=False)),
                ('ParlanteSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('IdProyector', models.AutoField(primary_key=True, serialize=False)),
                ('ProyectorSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Raton',
            fields=[
                ('IdRaton', models.AutoField(primary_key=True, serialize=False)),
                ('RatonSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('IdTeclado', models.AutoField(primary_key=True, serialize=False)),
                ('TecladoSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Distribucion', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('IdTipoMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('IdUps', models.AutoField(primary_key=True, serialize=False)),
                ('UpsSerial', models.CharField(max_length=200)),
                ('MarcaModelo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=200)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('IdMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaIngreso', models.DateField()),
                ('FechaSalida', models.DateField()),
                ('DescripcionMantenimiento', models.CharField(max_length=500)),
                ('IdEquipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo')),
                ('IdTipoMantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tipomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('IdLaboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Codigo', models.CharField(max_length=100)),
                ('Responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.estado'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.monitor'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Parlante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.parlante'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Raton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.raton'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Teclado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.teclado'),
        ),
    ]
