# Generated by Django 4.2.12 on 2024-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='encargados',
            fields=[
                ('IdEncargados', models.AutoField(primary_key=True, serialize=False)),
                ('Cedula', models.CharField(max_length=10)),
                ('NombreCompleto', models.CharField(max_length=200)),
            ],
        ),
    ]
