# Generated by Django 4.2.12 on 2024-05-15 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.case'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='IP',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.monitor'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Parlante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.parlante'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Raton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.raton'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='SistemaOperativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Teclado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.teclado'),
        ),
    ]
