# Generated by Django 4.2.12 on 2024-05-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('IdEncargados', models.AutoField(primary_key=True, serialize=False)),
                ('Cedula', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('IdEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('SistemaOperativo', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('IdLaboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=100)),
                ('Codigo', models.CharField(max_length=100)),
                ('Responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('IdMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('FechaIngreso', models.DateField()),
                ('FechaSalida', models.DateField()),
                ('DescripcionMantenimiento', models.CharField(max_length=500)),
                ('IdEquipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('IdTipoMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='encargados',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='IdTipoMantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.tipomantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.estado'),
        ),
    ]
