# Generated by Django 4.2.12 on 2024-05-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='IdEquipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo'),
        ),
    ]
