# Generated by Django 4.2.12 on 2024-05-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_mantenimiento_idequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomantenimiento',
            name='FechaIngreso',
        ),
        migrations.RemoveField(
            model_name='tipomantenimiento',
            name='Observacion',
        ),
    ]
